{{- if .Values.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- include "common.labels.component" "platform-operator" | nindent 4 }}
spec:
  ingress:
  - ports:
    {{- if .Values.webhook.enabled }}
    - port: {{ .Values.webhook.port }}
      protocol: TCP
    {{- end }}
    - port: {{ .Values.healthCheckPort }}
      protocol: TCP
  {{- if .Values.metrics.enabled }}
  - from:
    - podSelector:
        matchLabels:
          {{- toYaml .Values.metrics.podLabels | trimSuffix "\n" | nindent 10 }}
      {{- with .Values.metrics.namespaceLabels }}
      namespaceSelector:
        matchLabels:
          {{- toYaml . | trimSuffix "\n" | nindent 10 }}
      {{- end }}
    ports:
    - port: {{ .Values.metrics.port }}
      protocol: TCP
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  policyTypes:
  - Ingress
{{- end }}
